# -*- coding: utf-8 -*-
"""asi.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OeVe7vn6veY24OwyEUIj6Da05RTcrvFX
"""

# Intelligent Resume Screening System

!pip -q install scikit-learn

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

# Sample resumes
resumes = [
    "Experienced Python developer with machine learning and data analysis skills",
    "Frontend developer skilled in HTML CSS JavaScript React",
    "Data scientist with experience in Python, deep learning, NLP and AI"
]

# Job description
job_description = "Looking for a Python developer with machine learning and AI experience"

# Combine job description + resumes
documents = [job_description] + resumes

# Convert text into numerical vectors
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(documents)

# Compute similarity
similarity_scores = cosine_similarity(tfidf_matrix[0:1], tfidf_matrix[1:]).flatten()

# Create ranking
ranking = pd.DataFrame({
    "Resume": resumes,
    "Similarity Score": similarity_scores
}).sort_values(by="Similarity Score", ascending=False)

print("Resume Ranking Based on Job Description:\n")
print(ranking)